version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.11

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run API Test
          command: |
            pytest -m api

      - run:
          name: Run UI Test
          command: |
            pytest -m ui

      - store_artifacts:
          path: test-reports
          destination: /test-reports

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
