version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11

    working_directory: ~/Users/steshser/PycharmProjects/paycos_test

    steps:
      - checkout

      - run:
          name: Install libatk1.0-0
          command: |
            sudo apt-get update
            sudo apt-get install -y libatk1.0-0

      - run:
          name: Install Chrome and Firefox
          command: |
            CHROME_VERSION="118.0.5993.70"
            CHROME_URL="https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROME_VERSION/linux64/chrome-linux64.zip"
            curl -LO $CHROME_URL
            unzip chrome-linux64.zip
            sudo mv chrome-linux64/chrome /usr/local/bin/
            chrome --version

            sudo apt-get -y install firefox

      - run:
          name: Install Chrome WebDriver
          command: |
            CHROMEDRIVER_VERSION="118.0.5993.70"
            CHROMEDRIVER_URL="https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"
            curl -LO $CHROMEDRIVER_URL
            unzip chromedriver-linux64.zip
            sudo mv chromedriver /usr/local/bin/
            chromedriver --version

      - run:
          name: Install Firefox WebDriver
          command: |
           GECKODRIVER_VERSION="0.33.0"
            wget https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz -O /tmp/geckodriver.tar.gz
            tar -xzf /tmp/geckodriver.tar.gz -C /tmp
            sudo mv /tmp/geckodriver /usr/local/bin/geckodriver
            sudo chmod +x /usr/local/bin/geckodriver
            geckodriver --version

      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run API Test
          command: |
            pytest -m api

      - run:
          name: Run UI Test
          command: |
            pytest -m ui

      - store_artifacts:
          path: test-reports
          destination: /test-reports

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
