version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11

    working_directory: ~/Users/steshser/PycharmProjects/paycos_test

    steps:
      - checkout

      - run:
          name: Install Chrome WebDriver
          command: |
            LATEST_CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
            curl -o /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip
            unzip /tmp/chromedriver.zip -d /tmp
            sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
            sudo chmod +x /usr/local/bin/chromedriver
            chromedriver --version

      - run:
          name: Install Firefox WebDriver
          command: |
            LATEST_GECKODRIVER_VERSION=$(curl -sS https://github.com/mozilla/geckodriver/releases/latest | cut -d'"' -f2 | awk -F / '{print $7}')
            curl -o /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/$LATEST_GECKODRIVER_VERSION/geckodriver-$LATEST_GECKODRIVER_VERSION-linux64.tar.gz
            tar -xzf /tmp/geckodriver.tar.gz -C /tmp
            sudo mv /tmp/geckodriver /usr/local/bin/geckodriver
            sudo chmod +x /usr/local/bin/geckodriver
            geckodriver --version

      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run API Test
          command: |
            pytest -m api

      - run:
          name: Run UI Test
          command: |
            pytest -m ui

      - store_artifacts:
          path: test-reports
          destination: /test-reports

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
