version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11

    working_directory: ~/Users/steshser/PycharmProjects/paycos_test

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker Image
          command: |
            docker build -t paycos_test_browser_image -f docker-context/Dockerfile .
            docker images

      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run API Test
          command: |
            pytest -m api

      - run:
          name: Run UI Test
          command: |
            pytest -m ui

      - store_artifacts:
          path: test-reports
          destination: /test-reports

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
